apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: generic-device-plugin
  namespace: tailscale
  labels:
    app: generic-device-plugin
spec:
  selector:
    matchLabels:
      app: generic-device-plugin
  template:
    metadata:
      labels:
        app: generic-device-plugin
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
          effect: NoSchedule
      containers:
        - name: generic-device-plugin
          image: ghcr.io/squat/generic-device-plugin:latest
          args:
            - --device
            - '{"name": "tun", "groups": [{"paths": [{"path": "/dev/net/tun"}], "count": 1000}]}'
          resources:
            requests:
              cpu: 50m
              memory: 10Mi
            limits:
              cpu: 50m
              memory: 20Mi
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev
              mountPath: /dev
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev
          hostPath:
            path: /dev
