apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secret-store.yaml
  - external-secret.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - device-plugin.yaml
  - proxy-class.yaml
