apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - namespace.yaml
  - ../../base/redis
  - serviceaccount.yaml
  - secret-store.yaml
  - paradedb-image-catalog.yaml
  - cnpg-cluster.yaml
  - cnpg-pooler.yaml
  - cnpg-scheduled-backup.yaml
  - redis-backup-cronjob.yaml
  - redis-pod-monitoring.yaml
  - alerting-rules.yaml

patches:
  - path: redis-patch.yaml
    target:
      kind: StatefulSet
      name: redis
  - path: redis-exporter-patch.yaml
    target:
      kind: StatefulSet
      name: redis

labels:
  - pairs:
      environment: prod
      managed-by: kustomize
    includeSelectors: false
