apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  endpoints:
    - port: exporter
      path: /metrics
      interval: 30s
