apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
    # Relynce team members get admin access
    g, joseph@revelara.ai, role:admin
  scopes: '[email]'
