apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: joseph@revelara.ai
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - selector:
          dnsZones:
            - "i.revelara.ai"
        dns01:
          cloudDNS:
            project: incident-kb
            hostedZoneName: i-revelara-ai-public
      - selector:
          dnsZones:
            - "i.relynce.ai"
        dns01:
          cloudDNS:
            project: incident-kb
            hostedZoneName: i-relynce-ai-public
