apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.yaml
  - cluster-issuer.yaml
  - leader-election-rbac.yaml

patches:
  # Annotate cert-manager SA for Workload Identity
  - target:
      kind: ServiceAccount
      name: cert-manager
      namespace: cert-manager
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          iam.gke.io/gcp-service-account: cert-manager@incident-kb.iam.gserviceaccount.com
  # GKE Autopilot: move leader election out of kube-system
  - target:
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --leader-election-namespace=cert-manager
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --dns01-recursive-nameservers=8.8.8.8:53,8.8.4.4:53
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --dns01-recursive-nameservers-only
  - target:
      kind: Deployment
      name: cert-manager-cainjector
      namespace: cert-manager
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --leader-election-namespace=cert-manager
